import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen p-5">
        <div className="h-5/6 lg:flex">
          <div className="w-3/5 align-middle m-auto text-center">
            <h1 className="text-6xl font-bold">Create command pages for free</h1>
            <Link href="/login"><a className="btn m-auto mt-10 text-lg px-8" style={{ 'width': 'fit-content' }}>Start now</a></Link>
          </div>
          <div className="w-full h-full relative">
            <Image alt='' src="/dashboard_preview.png" height={1250} width={1967.25} objectFit="contain" />
          </div>
        </div>
        <div className="h-10 mt-16">
          <div className="flex h-10 mt-10 max-w-6xl m-auto">
            <div className="w-1/4 text-center relative">
              <Image className="m-auto filter grayscale" alt='' src="/logos/discord.svg" layout="fill" objectFit="contain" />
            </div>
            <div className="w-1/4 text-center relative">
              <Image className="m-auto filter grayscale" alt='' src="/logos/github.svg" layout="fill" objectFit="contain" />
            </div>
            <div className="w-1/4 text-center relative">
              <Image className="m-auto filter grayscale" alt='' src="/logos/slack.svg" layout="fill" objectFit="contain" />
            </div>
            <div className="w-1/4 text-center relative">
              <Image className="m-auto filter grayscale" alt='' src="/logos/telegram.svg" layout="fill" objectFit="contain" />
            </div>
          </div>
        </div>
      </div>

      <div>
        <div>
          <Image src="/triangle.svg" alt='' width="100%" height="10px"  layout="responsive"/>
          <div className="bg-primary text-white h-screen justify-center flex p-10">
            <div className="w-screen h-auto relative filter drop-shadow-xxl">
              <Image className="m-auto" alt='' src="/dashboard_preview.png" layout="fill" objectFit="contain" />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
