import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getUsers } from '../utils/users'
import { useEffect } from 'react'
import { useAuth } from '../utils/auth'

export default function Home() {
  const {user} = useAuth();

  useEffect(() => {
    getUsers().then(console.log)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {user?user.email:''}
      </div>

      <main className={styles.main}>
      <Link href="/login">Login</Link>
        <Link href="/register">Register</Link>
        <Link href="/create">Create App</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
